name: Test Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.26.0-17.6.pre'
          channel: 'beta'
      - name: Install dependencies
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Run tests
        run: flutter test --coverage
      - uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage/lcov.info
          min_coverage: 10
          token: ${{ secrets.GITHUB_TOKEN }}
