name: Web Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.3"
          channel: "stable"
      - name: Install dependencies
        run: |
          flutter config --enable-web
          flutter pub get
      - name: Build
        run: |
          flutter build web --dart-define=ENV=stage
          cp -R build/web/* web_public/public/
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P rti-charisma
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
